[Output]
Format=directory
Output=%d-%r-runtime

[Build]
Incremental=yes
BuildSources=%C/../..:hpc-ebpf-filter
WithNetwork=yes

[Content]
CleanPackageMetadata=false
Packages=
  elfutils-libelf
  zlib
  libzstd
BuildPackages=
  elfutils-libelf-devel
  zlib-devel
  libzstd-devel
  clang
  curl
  bash

[Include]
Include=%C/../base.conf
