[Distribution]
Distribution=ubuntu
Release=resolute

[Build]
BuildDirectory=%C/../../../target/mkosi.builddir
CacheDirectory=%C/../../../target/mkosi.cache

[Output]
Format=directory
OutputDirectory=%C/../../../target

[Content]
Packages=
    qemu-system-x86
    openssh-server
    openssh-client
    socat

[Include]
Include=mkosi-tools
