[Match]
Distribution=ubuntu

[Distribution]
Repositories=universe

[Content]
Packages=
    libelf1t64
    zlib1g
    libzstd1
BuildPackages=
    libelf-dev
    zlib1g-dev
    libzstd-dev
    curl
    bash
    ca-certificates
    build-essential
    pkgconf
