[Output]
OutputDirectory=%C/../target/mkosi.output

[Build]
ToolsTree=%C/../target/mkosi.tools
BuildDirectory=%C/../target/mkosi.builddir
CacheDirectory=%C/../target/mkosi.cache

[Content]
WithDocs=no
WithRecommends=no
