[Distribution]
Distribution=rocky
Release=10

[Build]
BuildDirectory=%C/../../../target/mkosi.builddir
CacheDirectory=%C/../../../target/mkosi.cache

[Output]
Format=directory
OutputDirectory=%C/../../../target

[Content]
Packages=
    qemu-kvm
    openssh
    openssh-clients
    socat

[Include]
Include=mkosi-tools
