[Output]
OutputDirectory=%C/../../target/mkosi.output

[Build]
BuildDirectory=%C/../../target/mkosi.builddir
CacheDirectory=%C/../../target/mkosi.cache

[Content]
WithDocs=no
WithRecommends=no
Format=directory

[Include]
Include=mkosi-tools

[Content]
Output=%a-%d-tools
