[Output]
Format=oci
Output=%d-%r-builder

[Content]
CleanPackageMetadata=false
PostInstallationScripts=%C/install-rust.sh
Packages=
  elfutils-libelf-devel
  zlib-devel
  libzstd-devel
  clang
  curl
  bash

[Include]
Include=%C/../base.conf
