[Output]
Format=disk
Output=%d-%r-vm
CompressOutput=no

[Runtime]
Console=native

[Content]
Autologin=yes
Bootable=yes
Bootloader=uki
Ssh=yes
Packages=
  kernel
  systemd
  systemd-boot
  dracut
  bash
  bpftool
  openssh-server

[Include]
Include=%C/../base.conf
