name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_mkosi_tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: sudo apt-get update

      - uses: systemd/mkosi@v26

      - name: Build mkosi tools
        run: |
          set -euo pipefail
          mkosi -C mkosi/tools build
          sudo tar -czf target/mkosi.tools.tar.gz target/mkosi.tools

      - name: Upload mkosi tools
        uses: actions/upload-artifact@v7
        with:
          path: target/mkosi.tools.tar.gz
          if-no-files-found: error
          archive: false

  build_and_test:
    strategy:
      matrix:
        include:
          - distro: rocky
            release: 9.7
      fail-fast: false
    needs: build_mkosi_tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: sudo apt-get update

      - uses: systemd/mkosi@v26

      - name: Setup systemd-machined
        run: |
          set -euo pipefail
          sudo apt-get install -y --no-install-recommends systemd-container
          sudo systemctl start systemd-machined

      - name: Download mkosi tools
        uses: actions/download-artifact@v8
        with:
          name: mkosi.tools.tar.gz
          path: target/

      - name: Extract mkosi tools
        run: |
          sudo tar -xzf target/mkosi.tools.tar.gz

      - name: Build VM
        run: |
          set -euo pipefail
          mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} genkey
          mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} build

      - name: Generate vmlinux.h
        run: |
          set -euo pipefail
          mkdir -p target/bpf_headers
          sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} vm >> vm.log 2>&1 &
          VM_PID=$!
          until sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} ssh -- true; do
            sleep 1
            if ! ps -p ${VM_PID} > /dev/null; then
                echo "VM failed to start"
                exit 1
            fi
          done
          sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} ssh -- bpftool btf dump file /sys/kernel/btf/vmlinux format c > target/bpf_headers/vmlinux.h
          sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} ssh -- systemctl poweroff
          wait ${VM_PID}

      - name: Upload vmlinux.h
        uses: actions/upload-artifact@v7
        with:
          name: vmlinux-${{ matrix.distro }}-${{ matrix.release }}.h
          path: target/bpf_headers/vmlinux.h
          if-no-files-found: error

      - name: Build program
        run: |
          set -euo pipefail
          mkosi -C mkosi/runtime --distribution ${{ matrix.distro }} --release ${{ matrix.release }} build

      - name: Test attaching
        run: |
          set -euo pipefail
          sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} vm >> vm.log 2>&1 &
          VM_PID=$!
          until sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} ssh -- true; do
            sleep 1
            if ! ps -p ${VM_PID} > /dev/null; then
                echo "VM failed to start"
                exit 1
            fi
          done
          sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} ssh -- "cat > /usr/local/bin/hpc-ebpf-filter && chmod +x /usr/local/bin/hpc-ebpf-filter" < target/mkosi.output/${{ matrix.distro }}-${{ matrix.release }}-runtime/usr/local/bin/hpc-ebpf-filter
          sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} ssh -- /usr/local/bin/hpc-ebpf-filter --test-attach
          sudo mkosi -C mkosi/vm --distribution ${{ matrix.distro }} --release ${{ matrix.release }} ssh -- systemctl poweroff
          wait ${VM_PID}

      - name: Upload program
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.distro }}-${{ matrix.release }}-hpc-ebpf-filter
          path: target/mkosi.output/${{ matrix.distro }}-${{ matrix.release }}-runtime/usr/local/bin/hpc-ebpf-filter
          if-no-files-found: error

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: vm.log
          name: ${{ matrix.distro }}-${{ matrix.release }}-logs

      - name: Build container image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          set -euo pipefail
          podman build \
            -t ghcr.io/${{ github.repository }}:${{ matrix.distro }}-${{ matrix.release }} \
            -f mkosi/runtime/Containerfile \
            --build-arg OUTPUT_DIR=${{ matrix.distro }}-${{ matrix.release }}-runtime \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.url=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.title=hpc-ebpf-filter" \
            --label "org.opencontainers.image.description=An eBPF LSM program to filter user actions on HPC systems" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "org.opencontainers.image.ref.name=${{ github.ref }}" \
            --label "org.opencontainers.image.licenses=GPL-3.0" \
            .
          podman save --format oci-archive ghcr.io/${{ github.repository }}:${{ matrix.distro }}-${{ matrix.release }} -o target/${{ matrix.distro }}-${{ matrix.release }}-image.tar

      - name: Upload container image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v7
        with:
          path: target/${{ matrix.distro }}-${{ matrix.release }}-image.tar
          archive: false

  push_container_image:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download container images
        uses: actions/download-artifact@v8
        with:
          pattern: "*-image.tar"

      - name: Push container images
        run: |
          set -euo pipefail
          echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io --username ${{ github.actor }} --password-stdin
          for IMAGE in *-image.tar; do
            podman image load --input "${IMAGE}"
            podman push ghcr.io/${{ github.repository }}:${IMAGE%-image.tar}
          done
